name: Release

env:
  GH_USER: jonaslagoni
  GH_EMAIL: <jonas-lt@live.dk>

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/GamingAPI/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Install dependencies
        run: dotnet restore
      - name: 'Automated Version Bump'
        uses: 'jonaslagoni/gh-action-dotnet-bump@main'
        id: version_bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          skip-tag: 'true'
          skip-commit: 'true'
          path-to-file: './